### PR TITLE
ComponentManager should just ignore unknown extra argument in the bas…

### LINKED ISSUE #85: rolling github workflow and Rpr job is failing.
see the following failures.

- https://github.com/ros2/domain_bridge/actions/runs/12551337060/job/34995593133?pr=84

```bash
/usr/bin/bash -c source /opt/ros/rolling/setup.sh && colcon build --symlink-install --packages-up-to domain_bridge --event-handlers=console_cohesion+
  ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.powershell_command': cannot import name 'OVERRIDE_OPT' from 'em' (/usr/local/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/entry_point.py", line 120, in load_entry_points
      extension_type = load_entry_point(entry_point)
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/entry_point.py", line 168, in load_entry_point
      return entry_point.load()
    File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2465, in load
      return self.resolve()
    File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/local/lib/python3.10/dist-packages/colcon_powershell/shell/powershell.py", line 17, in <module>
      from colcon_core.shell.template import expand_template
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/shell/template/__init__.py", line 19, in <module>
      raise e from None
    File "/usr/local/lib/python3.10/dist-packages/colcon_core/shell/template/__init__.py", line 10, in <module>
      from em import OVERRIDE_OPT
  ImportError: cannot import name 'OVERRIDE_OPT' from 'em' (/usr/local/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace
``` 

- https://build.ros2.org/job/Rpr__domain_bridge__ubuntu_noble_amd64/1/

### PR DESCRIPTION
**Pull request by fujitatomoya**
…e class.

closes https://github.com/ros2/domain_bridge/issues/85

introduced by https://github.com/ros2/rclcpp/pull/2685 (only rolling has this code)

### CODE REVIEW

File: rclcpp_components/src/component_manager.cpp [hunk 1]
```diff
@@ -223,9 +223,6 @@ ComponentManager::create_node_options(const std::shared_ptr<LoadNode::Request> r
             "Extra component argument 'enable_logger_service' must be a boolean");
       }
       options.enable_logger_service(extra_argument.get_value<bool>());
-    } else {
-      throw ComponentManagerException("Extra component argument '" + extra_argument.get_name() +
-          "' is not supported");
```
Comment (fujitatomoya) [inline rclcpp_components/src/component_manager.cpp:228]: this throw is added to check the unknown extra arguments in the base class.

but i do not think it should throw exception in the base class, instead it should ignore all unknown extra arguments in the base class. exception can only be thrown if the supported argument parameter type is unexpected just like before. so that child class can override this method to add more extra arguments to support. (it can actually try&catch the exception in the child class, but I think throwing exception is not correct here in the 1st place.)

this fixes the issue https://github.com/ros2/domain_bridge/issues/85

**Review by fujitatomoya — COMMENTED** [review]
@mjcarroll can you take a look? since you reviewed https://github.com/ros2/rclcpp/pull/2685?

**Comment by fujitatomoya** [comment]
rpr job says test also needs to be adjusted.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2723
Gist: https://gist.githubusercontent.com/fujitatomoya/4ba40095368841179e3ef1202b90f3db/raw/e78a92751445e97b6537afebb04c20b20dbfcaf1/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp_components
TEST args:  --packages-above rclcpp_components
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15046
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22362/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16625/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1893/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23154/)

**Review by alsora — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]
