### PR TITLE
[Humble] Implement Unified Node Interface (NodeInterfaces class) (backport #2041)

### LINKED ISSUE #2309: Backport request - Unified NodeInterfaces in Humble
## Feature request
I'd like to use a unified NodeInterfaces object  from https://github.com/ros2/rclcpp/pull/2041 under ROS2 Humble.

#### Feature description

Fuse uses https://github.com/ros2/rclcpp/pull/2041 as an extremely tidy way of [passing interfaces ](https://github.com/locusrobotics/fuse/blob/rolling/fuse_core/include/fuse_core/node_interfaces/node_interfaces.hpp) from the base node to its many pluginlib plugins.

I'm building a modular wrapper for GStreamer pipelines, intended to replace and unify gscam and audio_common, adding lots of features in the process.

A lot of complexity comes out of mapping the Properties of GStreamer Elements to Parameters on the Node, and I need `ParameterEventHandler::add_parameter_callback` to separate the rclcpp parameter validate and update stages to allow GStreamer elements to validate properties before accepting them.

[ParameterEventHandler](http://docs.ros.org/en/humble/p/rclcpp/generated/classrclcpp_1_1ParameterEventHandler.html#class-parametereventhandler) needs a `NodeT` macro type in its constructor, and satisfying that is making a mess of my ROS2 version portability.

#### Implementation considerations

https://github.com/ros2/rclcpp/pull/2041 appears to be the complete picture, I haven't found any discussion of why a back-port wouldn't be possible

### PR DESCRIPTION
**Pull request by fabianhirmann**
## Description

This is a backport of #2041 to Humble to use the new nice `NodeInterfaces` class there as well.

Fixes #2309

### Is this user-facing behavior change?

No, previously existing behavior is not changed. 

### Did you use Generative AI?

No.

### Additional Information

Interestingly the `NodeInterfaces` class is also already documented for ROS Humble but has not been backported to Humble yet:
https://docs.ros.org/en/humble/Tutorials/Intermediate/Using-Node-Interfaces-Template-Class.html

### CODE REVIEW

**Review by alsora — APPROVED** [review]
Looks good to me.
The PR is made of only additions and no changes to existing classes so it's safe to backport.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rclcpp#3002
Gist: https://gist.githubusercontent.com/ahcorde/c0e6f29e8411e6cf7f531da6b3b2ac28/raw/4d0f5b268275411fab4ce323121d9c484220cfe6/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp rclcpp_lifecycle
TEST args:  --packages-above rclcpp rclcpp_lifecycle
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17709
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26452/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20079/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6214/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26159/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
I can see here some build errors https://ci.ros2.org/job/ci_linux-rhel/6214/console

**Comment by fabianhirmann** [comment]
Thank you @ahcorde for your comment! I think I fixed the issue now. I am still wondering that the same issue did not appear locally on my system (Ubuntu 22.04) as well as at the PR on the rolling branch but I believe it must be because of different compilers or compiler options. In any case, please have another look on it!

**Comment by ahcorde** [comment]
Pulls: ros2/rclcpp#3002
Gist: https://gist.githubusercontent.com/ahcorde/95e3be6be08b5dc37b6e5ad52653ef7c/raw/4d0f5b268275411fab4ce323121d9c484220cfe6/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp rclcpp_lifecycle
TEST args:  --packages-above rclcpp rclcpp_lifecycle
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17720
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26464/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20107/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6227/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26170/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26478/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20109/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6241/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26184/)

**Comment by fabianhirmann** [comment]
Hi @ahcorde!

Is there something blocking this PR from getting merged? Or is there something else I can do to support the progress of this PR?

Thanks,
Fabian

**Review by ahcorde — CHANGES_REQUESTED** [review]
> Hi @ahcorde!
> 
> Is there something blocking this PR from getting merged? Or is there something else I can do to support the progress of this PR?
> 
> Thanks, Fabian

There are some consistent tests failures, can you check if these tests are related with this PR ?

**Comment by jmachowinski** [comment]
This seems to miss the changes done recently to the signal handling. A rebase should fix the tests.

**Comment by fabianhirmann** [comment]
> This seems to miss the changes done recently to the signal handling. A rebase should fix the tests.

Thank you @jmachowinski! I rebased my branch now. @ahcorde Could you trigger another build? Thanks!

In the meanwhile I also checked the failed tests and the comment of @jmachowinski makes sense. The following tests failed:
- 21 - test_sigint_handler_before_shutdown__rmw_connextdds
- 23 - test_sigterm_handler_before_shutdown__rmw_connextdds
- 48 - test_sigint_handler_before_shutdown__rmw_cyclonedds_cpp
- 50 - test_sigterm_handler_before_shutdown__rmw_cyclonedds_cpp
- 75 - test_sigint_handler_before_shutdown__rmw_fastrtps_cpp
- 77 - test_sigterm_handler_before_shutdown__rmw_fastrtps_cpp

**Comment by ahcorde** [comment]
Pulls: ros2/rclcpp#3002
Gist: https://gist.githubusercontent.com/ahcorde/fb9a0932af7680b9af0c08d494aa901d/raw/4d0f5b268275411fab4ce323121d9c484220cfe6/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp rclcpp_lifecycle
TEST args:  --packages-above rclcpp rclcpp_lifecycle
ROS Distro: humble
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17818
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26684/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20254/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6473/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26266/)

**Comment by fabianhirmann** [comment]
> Pulls: #3002 Gist: https://gist.githubusercontent.com/ahcorde/fb9a0932af7680b9af0c08d494aa901d/raw/4d0f5b268275411fab4ce323121d9c484220cfe6/ros2.repos BUILD args: --packages-above-and-dependencies rclcpp rclcpp_lifecycle TEST args: --packages-above rclcpp rclcpp_lifecycle ROS Distro: humble Job: ci_launcher ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17818
>     * Linux [Build Status](http://ci.ros2.org/job/ci_linux/26684/)
>     * Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20254/)
>     * Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6473/)
>     * Windows [Build Status](http://ci.ros2.org/job/ci_windows/26266/)

Thank you @ahcorde for running the build again! I see that linux-rhel is still unstable but I do not see any relation to my PR.

The errors at linux-rhel are in the following packages where I believe in both cases it is because RHEL has an older version of python (3.6 compared to 3.10 on Ubuntu 22.04):
- message_filters
  - `ModuleNotFoundError: No module named 'dataclasses'`
  - I think this was introduced in https://github.com/ros2/message_filters/pull/216
- test_launch_ros
  - `yaml.FullLoader` does not exist
  - This code is already there for quite a while so I am not sure if this ever worked on RHEL to be honest
  - The exact error is:
 ________________ TestNode.test_launch_node_with_parameter_dict _________________
15:46:04 test/test_launch_ros/actions/test_node.py:229: in test_launch_node_with_parameter_dict
15:46:04     expanded_parameters_dict = yaml.load(h, Loader=yaml.FullLoader)
15:46:04 E   AttributeError: module 'yaml' has no attribute 'FullLoader'

**Review by ahcorde — APPROVED** [review]
